version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: rsha-container
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: rsha
    volumes:
      - pgdata:/bitnami/postgresql
    restart: unless-stopped

volumes:
  pgdata: