// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // migrate precisa de conexão direta (DDL + advisory lock, não passa por pooler).
    // O runtime usa DATABASE_URL separadamente, via adapter em lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
